### ISSUE TITLE
OpenCMISS-Zinc API docs not showing current develop branch

### ISSUE THREAD

**Issue by rchristie** [OpenCMISS/website#57]
The OpenCMISS-Zinc API documentation should be showing the develop branch and be continuously up-to-date with changes to it. The current Zinc API docs are more than a year out of date.

**Comment by chrispbradley** [comment]
Noel @inkybutton was looking at this just before the Christmas break. Has has updated this but had a problem because the build slave required an OS upgrade. He was waiting for IT to do it. Not sure what the current state of the situation is.

**Comment by inkybutton** [comment]
Hi @chrispbradley, by @rchristie 's description it seems to be a different issue. I will need to look into this.

**Comment by inkybutton** [comment]
It seems the problem is the OpenCMISS website is currently tracking Zinc's "devel" branch when building API doc. I think this is what was agreed. It seems another branch was created ("develop") where new commits are being made. The last commit to devel was made in April, whereas the last commit to develop was made in December.
Would you like me to change the build so that we are tracking the develop branch instead?

**Comment by chrispbradley** [comment]
Yes, develop is the new devel. The Iron developers API should also look at develop.

**Comment by inkybutton** [comment]
The Zinc API documentation on staging should now be updated to track develop branch, please take a look: http://staging.opencmiss.org/documentation.html I will now create a PR to merge changes into master (i.e. www.opencmiss.org), please OK it if you're happy with the generated API documentation.

**Comment by rchristie** [comment]
Looks good to me.

**Comment by inkybutton** [comment]
The website build is now tracking develop branch Zinc API documentation.
